name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        python -m pytest tests/ -v
    
    - name: Check code formatting
      run: |
        black --check .
        flake8 .
    
    - name: Test basic functionality
      run: |
        python -c "from agents.planner_agent import PlannerAgent; print('Planner Agent imported successfully')"
        python -c "from agents.executor_agent import ExecutorAgent; print('Executor Agent imported successfully')"
        python -c "from agents.verifier_agent import VerifierAgent; print('Verifier Agent imported successfully')"
        python -c "from agents.supervisor_agent import SupervisorAgent; print('Supervisor Agent imported successfully')" 